In [1]:
import numpy as np
my_vector1 = np.array([1,2,3,4,5])
print("My vector: ", my_vector1)

My vector:  [1 2 3 4 5]


In [2]:
import numpy as np
my_vector2 = np.arange(5)
my_vector3 = np.arange(0, 10, 2)
print("My vector2: ", my_vector2)
print("My vector3: ", my_vector3)

My vector2:  [0 1 2 3 4]
My vector3:  [0 2 4 6 8]


In [4]:
import numpy as np
my_vector4 = np.linspace(1, np.pi, 4)
print("My vector4: ", my_vector4)


My vector4:  [1.         1.71386422 2.42772844 3.14159265]


In [5]:
import numpy as np
my_vector4 = np.arange(5)
new_vector = np.append(my_vector4, [1000])
print("New vector with 1000 at the end: ", new_vector)

New vector with 1000 at the end:  [   0    1    2    3    4 1000]


In [6]:
import numpy as np
my_vector4 = np.arange(5)
new_vector_insert = np.insert(my_vector4, 1, 8888)
print("Vector with value 8888 at the index 1: ", new_vector_insert)

Vector with value 8888 at the index 1:  [   0 8888    1    2    3    4]


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5])
index = 0
arr2 = np.delete(arr, index)
print("Based array: ", arr, "Array with removed value[0]: ", arr2)

Based array:  [1 2 3 4 5] Array with removed value[0]:  [2 3 4 5]


In [9]:
import numpy as np
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([1,2,3,4,5])
adding1 = np.add(vec1, vec2)
adding2 = vec1 + vec2
print("After adding using function: ", adding1)
print("After adding without function: ", adding2)

After adding using function:  [ 2  4  6  8 10]
After adding without function:  [ 2  4  6  8 10]


In [14]:
import numpy as np
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([5,4,3,2,1])
subtract1 = np.subtract(vec1, vec2)
subtract2 = vec1 - vec2
print("After subtracting using function: ", subtract1)
print("After subtracting without function: ", subtract2)

After subtracting using function:  [-4 -2  0  2  4]
After subtracting without function:  [-4 -2  0  2  4]


In [15]:
import numpy as np
vec1 = np.array([1,2,3,4,5])
scalar = 3
result = vec1 * scalar
print(result)

[ 3  6  9 12 15]


In [16]:
import numpy as np
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([0,2,3,0,2])
multiply1 = np.multiply(vec1, vec2)
multiply2 = vec1 * vec2
print("After multipled using function: ", multiply1)
print("After multipled without function: ", multiply2)

After multipled using function:  [ 0  4  9  0 10]
After multipled without function:  [ 0  4  9  0 10]


In [18]:
import numpy as np
vec1 = np.array([1,2,3,4,15])
vec2 = np.array([1,2,3,2,5])
divide1 = np.divide(vec1, vec2)
divide2 = vec1 / vec2
print("After divide using function: ", divide1)
print("After divide without function: ", divide2)

After divide using function:  [1. 1. 1. 2. 3.]
After divide without function:  [1. 1. 1. 2. 3.]


In [21]:
import numpy as np
matrix1 = np.array([[1,2,3,4,15], [2,4,6,8,10]])
print(matrix1)

[[ 1  2  3  4 15]
 [ 2  4  6  8 10]]


In [27]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
import numpy as np
m = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
x = np.matrix(m)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
first_value = x[0][0]
middle_value = x[1][1]
last_value = x[-1][-1]
print("first element in matrix", first_value)
print("middle element in matrix", middle_value)
print("last element in matrix", last_value)

first element in matrix 1
middle element in matrix 5
last element in matrix 9


In [35]:
import numpy as np
a = np.diag((1,2,3,4))
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
import numpy as np
zeros = np.zeros((3,3))
print(zeros)
ones = np.ones((3,3))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
x = zeros.copy()
x[0][2] = 6
print(x)

[[0. 0. 6.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
%pip install tensorflow
import tensorflow as tf
t1 = tf.constant([1,2,3])
t2 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])
t3 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t4 = tf.constant(["String_one", "String_two", "String_three"])
print(t1)
print("\n")
print(t2)
print("\n")
print(t3)
print("\n")
print(t4)

Note: you may need to restart the kernel to use updated packages.
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


tf.Tensor(
[[1.1 2.2 3.3]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


tf.Tensor([b'String_one' b'String_two' b'String_three'], shape=(3,), dtype=string)
