In [6]:
import numpy as np
# Zadanie1

vec1 = np.array([1,4,5,6,2,1,5,6,7,0])
vec1 = np.delete(vec1, 5)
print(vec1)
vec1 = np.append(vec1, [8])
print(vec1)
vec1[1::2] += 2
print(vec1)
vec1 = vec1[::-1]
print(vec1)

[1 4 5 6 2 5 6 7 0]
[1 4 5 6 2 5 6 7 0 8]
[ 1  6  5  8  2  7  6  9  0 10]
[10  0  9  6  7  2  8  5  6  1]


In [8]:
import numpy as np
# Zadanie2

vec1 = np.array([1, 2, 3, 4, 5])
list1 = [1, 2, 3, 4, 5]

scalar = 2

# mnożenie wektora przez skalar w NumPy
vec1_scalar = vec1 * scalar
print(vec1_scalar)

# mnożenie listy przez skalar w Pythonie
list1_scalar = [x * scalar for x in list1]
print(list1_scalar)

# Jak widać, w przypadku wektora w NumPy mnożenie przez skalar działa na każdym elemencie oddzielnie, a wynik jest zwracany jako nowy wektor NumPy. W przypadku listy w Pythonie mnożenie przez skalar działa na całej liście jako jednej całości, a wynik jest zwracany jako nowa lista Pythona


[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [15]:
# Zadanie3
import numpy as np

matrix = np.array([3,5,0,2,6,1,3,8,9]).reshape(3,3)
print(matrix,"\n")
matrix[0][0] = -2
print(matrix,"\n")
matrix[1][1] = 44
print(matrix,"\n")
matrix[-1][-1] = 0
print(matrix)

[[3 5 0]
 [2 6 1]
 [3 8 9]] 

[[-2  5  0]
 [ 2  6  1]
 [ 3  8  9]] 

[[-2  5  0]
 [ 2 44  1]
 [ 3  8  9]] 

[[-2  5  0]
 [ 2 44  1]
 [ 3  8  0]]


In [18]:
# Zadanie4
import numpy as np

matrix = np.array([3,5,0,2,6,1,3,8,9]).reshape(3,3)
even_index= np.arange(0, matrix.size, 2)  # indeksy parzyste
matrix.flat[even_index] = 0  # przypsuje wartość 0 do indeksów parzystych
print(matrix)

[[0 5 0]
 [2 0 1]
 [0 8 0]]


In [38]:
# Zadanie5
import numpy as np

matrix1 = np.array([2,1,1,1,3,6,4,5,5]).reshape(3,3)
matrix2 = np.array([1,0,5,2,1,6,0,3,0]).reshape(3,3)
print(matrix1)
print("    +")
print(matrix2,"\n")

sum = np.zeros((3, 3))  # macierz wynikowa wypełniona zerami

for i in range(3):
    for j in range(3):
        sum[i][j] = matrix1[i][j] + matrix2[i][j]

print(sum)

[[2 1 1]
 [1 3 6]
 [4 5 5]]
    +
[[1 0 5]
 [2 1 6]
 [0 3 0]] 

[[ 3.  1.  6.]
 [ 3.  4. 12.]
 [ 4.  8.  5.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
# Zadanie6
import numpy as np
import tensorflow as tf

tensor = tf.constant(np.arange(1,17,1).reshape(4,4)) #macierz 4x4 o elementach od 1 do 16
print(tensor)

# Otrzymaliśmy tensor o wymiarach 4x4 który jest dwuwymiarową strukturą danych, która przechowuje 16 liczb całkowitych z zakresu od 1 do 16, uporządkowanych w 4 kolumnach i 4 wierszach. Tensor ten ma również typ danych int32, który jest domyślnym typem danych w TensorFlow dla liczb całkowitych.

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)
