In [1]:
import numpy as np

A = np.array([2,1,1,1,3,6,4,5,5]).reshape(3,3)
B = np.array([1,0,5,2,1,6,0,3,0]).reshape(3,3)

C = np.dot(A,B)
print("Mnożenie za pomocą np.dot() \n", C)

D = np.matmul(A,B)
E = A@B

print("Mnożenie za pomocą np.matmul() \n", D)
print("Mnożenie za pomocą operatora @ \n", C)


Mnożenie za pomocą np.dot() 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]
Mnożenie za pomocą np.matmul() 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]
Mnożenie za pomocą operatora @ 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]


In [6]:
import numpy as np

A = np.array([[6,1,1,4],
             [4,-2,5,1],
             [2,8,7,4],
             [2,2,1,3]])

#rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A)) #rząd

Rank of A: 4


In [7]:
import numpy as np

A = np.array([[6,1,1],
              [4,-2,5],
              [2,8,7]])

#wyznacznik macierzy
print("\nDeterminant of A:",np.linalg.det(A))


Determinant of A: -306.0


In [8]:
import numpy as np

A = np.array([[4,3,2,0],
              [-4,-2,-5,1],
              [12,8,-7,4]])

M = np.transpose(A)
print(M)

[[ 4 -4 12]
 [ 3 -2  8]
 [ 2 -5 -7]
 [ 0  1  4]]


In [9]:
#ZADANIA

In [17]:
import numpy as np

def multiply_matrices(A, B): #zdefiniowanie funkcji przyjmującej macierze A i B jako argumenty
    if A.shape[1] != B.shape[0]: #Warunek sprawdzający czy liczba kolumn macierzy "A" jest równa liczbie wierszy macierzy "B".
        print("Nieprawidłowe wymiary macierzy")
        return None #Jeśli warunek z linii 4 nie jest spełniony, wypisuje komunikat o nieprawidłowych wymiarach macierzy i zwraca wartość "None".
    else:
        #W przeciwnym wypadku tworzona jest macierz wynikowa "C" o wymiarach równych liczbie wierszy macierzy "A" i liczbie #kolumn macierzy "B".
        C = np.zeros((A.shape[0], B.shape[1]))

        # mnożenie macierzy za pomocą pętli
        #W kolejnych trzech pętlach "for" mnożone są elementy macierzy "A" i "B" zgodnie z zasadą mnożenia macierzy, a wynik zapisywany jest w odpowiednim miejscu macierzy wynikowej "C".
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(A.shape[1]):
                    C[i][j] += A[i][k] * B[k][j]
        return C #Funkcja zwraca wynik w postaci macierzy "C".

A = np.array([[2, 1, 1], [1, 3, 6], [4, 5, 5]])
B = np.array([[1, 0, 5], [2, 1, 6], [0, 3, 0]])

C = multiply_matrices(A, B) #mnożenie macierzy A i B za pomocą zdefiniowanej funkcji
print(C) #wyświetlenie wyniku

[[ 4.  4. 16.]
 [ 7. 21. 23.]
 [14. 20. 50.]]


In [15]:
def determinant(matrix): #zdefiniowanie funkcji przyjmującej macierz jako argument
    if len(matrix) != 3 or len(matrix[0]) != 3: #Warunek sprawdzający, czy wymiary macierzy są równe 3x3
        print("Nieprawidłowy wymiar macierzy")
        return None #Jeśli warunek z linii 2 nie jest spełniony, wypisuje komunikat o nieprawidłowych wymiarach macierzy i zwraca wartość "None".
    else: #W przeciwnym wypadku przypisuje elementy macierzy do zmiennych "a", "b", "c", "d", "e", "f", "g", "h" i "i".
        a, b, c = matrix[0]
        d, e, f = matrix[1]
        g, h, i = matrix[2]

        det = a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h #Oblicza wyznacznik macierzy "det" zgodnie ze wzorem Sarusa na wyznacznik macierzy 3x3

        return det #Funkcja zwraca wyznacznik "det".

matrix = [[1, 4, 5], [2, 1, 6], [0, 3, 2]] #utworzenie macierzy 3x3

det = determinant(matrix) #wywołanie funkcji obliczającej wyznacznik na macierzy
print(det) #wyświetlenie wyniku

-2


In [3]:
def transpose(matrix): #zdefiniowanie funkcji przyjmującej macierz jako argument
    transposed = [] #utworzenie pustej listy, która będzie przechowywać wynikowe transponowane elementy macierzy
    for i in range(len(matrix[0])): #pętla "for" iterująca po indeksach kolumn macierzy
        row = [] #utworzenie pustej listy "row", która będzie przechowywać wiersz transponowanej macierzy
        for j in range(len(matrix)): #pętla "for" iterująca po indeksach wierszy macierzy
            row.append(matrix[j][i]) #Dodanie elementu o indeksie (j, i) do listy "row"
        transposed.append(row) #dodanie listy "row" do listy "transposed"
    
    for row in transposed: #pętla "for" iterująca po wierszach transponowanej macierzy
        print(row) #wyświetlenie każdego wiersza macierzy



matrix = [[3,2,4,1,8,0], [2,3,5,6,0,3],[7,7,2,1,4,5]] #inicjacja macierzy
transpose(matrix) #wywołanie funkcji transponującej macierz


[3, 2, 7]
[2, 3, 7]
[4, 5, 2]
[1, 6, 1]
[8, 0, 4]
[0, 3, 5]
